### PR TITLE
Proper Python packaging

### PR DESCRIPTION
**Pull request by brentyi**
For cleaner install/uninstall, dependency management, etc

Possible next steps after this is merged:
- Clean up demos?
- Resolve TODOs in blue_interface.py?
- Automate doc generation/publishing? Is this all manual right now?

@wuphilipp @gbalke for testing/review

### CODE REVIEW

**Comment by wuphilipp** [comment]
Ya sounds like a good plan. Should we have a separate repo for internal demos like the waypoint and Chebyshev scripts?

**Comment by gbalke** [comment]
Should we just return internal demos to the internal repo? Seems like not much for an entire repo.

**Comment by brentyi** [comment]
Moving internal demos makes sense to me; the examples in this repo should probably be limited to super barebones examples.

**Comment by gbalke** [comment]
Agreed

**Pull request merged**
